import { Vehicle, DriverScore, Ctrc, Expense, Ticket, CriticClient, Occurence } from './types';

export const initialVehicles: Vehicle[] = [
  {
    id: 'RTA3G45',
    driverName: 'João Silva',
    capacity: '3/4 - 4.5t',
    type: 'Baú Seco',
    status: 'Em Rota',
  },
  {
    id: 'OPR1B22',
    driverName: 'Maria Oliveira',
    capacity: 'Toco - 6t',
    type: 'Refrigerado',
    status: 'Disponível',
  },
  {
    id: 'LOG9H88',
    driverName: 'Não designado',
    capacity: 'VUC - 3t',
    type: 'Baú Seco',
    status: 'Manutenção',
  },
  {
    id: 'FLT8M55',
    driverName: 'Carlos Silva',
    capacity: 'Bitrem - 57t',
    type: 'Sider',
    status: 'Em Rota',
  },
  {
    id: 'TRK4X90',
    driverName: 'Ana Martins',
    capacity: 'VUC - 3.5t',
    type: 'Baú Seco',
    status: 'Disponível',
  },
];

export const initialDrivers: DriverScore[] = [
  {
    id: 'MOT-8842',
    name: 'Carlos Silva',
    score: 94,
    bestRoute: 'São Paulo - Z. Sul',
    status: 'Excelente',
    vehicle: 'Mercedes Sprinter (ABC-1234)',
    avgTime: 14,
    errorRate: 1.2,
    successRate: 98.5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'MOT-1109',
    name: 'Ana Martins',
    score: 88,
    bestRoute: 'Campinas Exp.',
    status: 'Bom',
    vehicle: 'Volkswagen Delivery (VUC-3344)',
    avgTime: 18,
    errorRate: 1.8,
    successRate: 95.0,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'MOT-2911',
    name: 'Roberto Costa',
    score: 72,
    bestRoute: 'SP - Centro',
    status: 'Regular',
    vehicle: 'Volvo VM 330 (XYZ-9876)',
    avgTime: 23,
    errorRate: 2.5,
    successRate: 91.2,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'MOT-5590',
    name: 'Fernando Alves',
    score: 45,
    bestRoute: 'Guarulhos Ind.',
    status: 'Atenção',
    vehicle: 'Scania R450 (ABC-5566)',
    avgTime: 34,
    errorRate: 4.8,
    successRate: 85.4,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
  },
];

export const initialAvailableCtrcs: Ctrc[] = [
  {
    id: 'SPO683890-1',
    destinatario: '28.223.989 RICARD',
    cidade: 'ALFENAS, MG',
    weight: 80.8,
    volume: 5,
    type: 'NORMAL',
    status: 'Disponível',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '25/05/2026',
    remetente: 'FAB.ELASTICOS S',
    ocorrencia: '57 CONFE OK',
    data_ocorr: '22/05/2026',
    nf: '174795',
    valor: 8389.42,
    frete: 340.05,
    unid: 'SPO',
    pagador: 'FAB.ELASTICOS S (REMETENTE)',
    cod: 'C-083890',
    descricao_ocorr: 'CONFERENCIA CONCLUIDA COM SUCESSO',
    data_ocorrencia: '22/05/2026',
    peso_r: 80.8,
    obs: 'Mercadoria frágil - Paletizada',
    disponibilidade: 'DISPONÍVEL',
    localizacao: 'BOX 02 - SETOR NORTE',
  },
  {
    id: 'PPY389007-4',
    destinatario: '64.647.937 ANDRE',
    cidade: 'ALFENAS, MG',
    weight: 23.201,
    volume: 3,
    type: 'NORMAL',
    status: 'Em Rota',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '25/05/2026',
    remetente: 'PROQUALIT TELE',
    ocorrencia: '2 MERC MERC',
    data_ocorr: '22/05/2026',
    nf: '191512',
    valor: 2959.57,
    frete: 76.41,
    unid: 'PPY',
    pagador: '64.647.937 ANDRE (DESTINATÁRIO)',
    cod: 'C-389007',
    descricao_ocorr: 'MERCADORIA EM TRÂNSITO PARA FILIAL',
    data_ocorrencia: '22/05/2026',
    peso_r: 23.201,
    obs: 'Urgente para entrega matinal',
    disponibilidade: 'EM TRÂNSITO',
    localizacao: 'BOX 02 - MEZANINO B',
  },
  {
    id: 'SPO684122-2',
    destinatario: 'A.P. AUTO PECAS E',
    cidade: 'ALFENAS, MG',
    weight: 147.35,
    volume: 13,
    type: 'CURVA A',
    status: 'Transferência',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '26/05/2026',
    remetente: 'FORT LUB PRODI',
    ocorrencia: '69 CHEGA CHEGA',
    data_ocorr: '21/05/2026',
    nf: '1476',
    valor: 7034.12,
    frete: 191.31,
    unid: 'SPO',
    pagador: 'FORT LUB PRODI (REMETENTE)',
    cod: 'C-084122',
    descricao_ocorr: 'MERCADORIA CHEGOU NA FILIAL',
    data_ocorrencia: '21/05/2026',
    peso_r: 147.35,
    obs: 'Atenção ao manuseio - Caixa pesada',
    disponibilidade: 'RESERVADO',
    localizacao: 'BOX 14 - CORREDOR CENTRO',
  },
  {
    id: 'ALF112233-0',
    destinatario: 'AGROFARM VETSH',
    cidade: 'ALFENAS, MG',
    weight: 25,
    volume: 1,
    type: 'NORMAL',
    status: 'Disponível',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '25/05/2026',
    remetente: 'ACESSORIOS DU',
    ocorrencia: '57 CONFE OK',
    data_ocorr: '22/05/2026',
    nf: '11108',
    valor: 632.12,
    frete: 104.46,
    unid: 'ALF',
    pagador: 'AGROFARM VETSH (DESTINATÁRIO)',
    cod: 'C-112233',
    descricao_ocorr: 'CONFERENCIA CONCLUIDA COM SUCESSO',
    data_ocorrencia: '22/05/2026',
    peso_r: 25.0,
    obs: 'Nenhuma observação',
    disponibilidade: 'DISPONÍVEL',
    localizacao: 'BOX 02 - PRATELEIRA A3',
  },
  {
    id: 'SPO685599-9',
    destinatario: 'NATUS FARMA CON',
    cidade: 'ALFENAS, MG',
    weight: 4.98,
    volume: 3,
    type: 'NORMAL',
    status: 'Agendamento',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 99',
    prev_ent: '25/05/2026',
    remetente: 'CREMER S A',
    ocorrencia: '15 ENTRE ENTRE',
    data_ocorr: '20/05/2026',
    nf: '513157',
    valor: 811.67,
    frete: 328.27,
    unid: 'SPO',
    pagador: 'CREMER S A (REMETENTE)',
    cod: 'C-085599',
    descricao_ocorr: 'AGENDAMENTO DE ENTREGA SOLICITADO',
    data_ocorrencia: '20/05/2026',
    peso_r: 4.98,
    obs: 'Agendamento prévio necessário',
    disponibilidade: 'BLOQUEADO',
    localizacao: 'BOX 99 - CHÃO SETOR EXTRA',
  },
  {
    id: 'VAG998877-1',
    destinatario: 'REGINA HELENA BE',
    cidade: 'ALFENAS, MG',
    weight: 6.8,
    volume: 1,
    type: 'NORMAL',
    status: 'Em Rota',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '22/05/2026',
    remetente: 'COMERCIAL FRIG',
    ocorrencia: '2 MERC MERC',
    data_ocorr: '22/05/2026',
    nf: '126125',
    valor: 666.36,
    frete: 71.7,
    unid: 'VAG',
    pagador: 'COMERCIAL FRIG (REMETENTE)',
    cod: 'C-998877',
    descricao_ocorr: 'MERCADORIA EM TRÂNSITO PARA FILIAL',
    data_ocorrencia: '22/05/2026',
    peso_r: 6.8,
    obs: 'Manter refrigerado se aplicável',
    disponibilidade: 'EM TRÂNSITO',
    localizacao: 'BOX 02 - SETOR SUL',
  },
];

// Romaneio page linked CTRCs:
export const initialLinkedCtrcs: Ctrc[] = [
  {
    id: '39281-A',
    destinatario: 'Indústrias Matarazzo',
    cidade: 'São Paulo, SP',
    weight: 1250,
    volume: 3.5,
    type: 'NORMAL',
    status: 'Entregue',
  },
  {
    id: '39282-B',
    destinatario: 'Comercial Silva Ltda',
    cidade: 'Campinas, SP',
    weight: 840,
    volume: 2.1,
    type: 'NORMAL',
    status: 'Entregue',
  },
  {
    id: '39283-C',
    destinatario: 'Distribuidora XYZ',
    cidade: 'Ribeirão Preto, SP',
    weight: 3100,
    volume: 6.2,
    type: 'CURVA A',
    status: 'Recusado',
  },
  {
    id: '39284-D',
    destinatario: 'Armazéns Gerais S.A.',
    cidade: 'Uberlândia, MG',
    weight: 4500,
    volume: 8.5,
    type: 'NORMAL',
    status: 'Pendente',
  },
];

export const initialExpenses: Expense[] = [
  { id: 'exp-1', description: 'Descarga Manual (Cliente B)', value: 150.00 },
  { id: 'exp-2', description: 'Borracharia BR-116', value: 85.50 },
];

export const initialOccurrences: Occurence[] = [
  {
    id: 'occ-1',
    title: 'Cliente Ausente / Recusa',
    time: 'Hoje, 14:30',
    description: 'Relacionado ao CTRC 39283-C. Portaria informou que o responsável não estava.',
    type: 'error',
  },
  {
    id: 'occ-2',
    title: 'Atraso na Carga',
    time: 'Ontem, 08:15',
    description: 'Veículo liberado com 2 horas de atraso no CD Origem devido a sistema inoperante.',
    type: 'neutral',
  },
];

export const initialTickets: Ticket[] = [
  {
    id: '#TRK-99281A',
    title: 'Cliente ausente (3ª tentativa)',
    destinatario: 'João Silva',
    address: 'R. das Flores, 123 - Centro',
    ageMinutes: 15,
    priority: 'Prioridade Alta',
    status: 'Pendente',
    icon: 'error',
  },
  {
    id: '#TRK-77342B',
    title: 'Endereço não localizado',
    destinatario: 'Maria Oliveira',
    address: 'Av. Principal, S/N - Zona Rural',
    ageMinutes: 45,
    status: 'Pendente',
    icon: 'wrong_location',
  },
];

export const initialCriticalClients: CriticClient[] = [
  {
    id: 'CDCD-01',
    prefix: 'CD',
    name: 'Centro Dist. Norte',
    score: 98,
    rejections30d: 12,
    avgQueueTime: '4h 30m',
    address: 'Zona Industrial II, São Paulo',
    recurrentIssues: [
      {
        title: 'Recusa carga após as 16h',
        description: 'Rigidez extrema na janela de recebimento.',
        icon: 'block',
      },
      {
        title: 'Fila de espera excessiva',
        description: 'Média histórica de 4h30m de doca presa.',
        icon: 'hourglass_empty',
      },
    ],
    auditUser: 'Carla M.',
    auditAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=128',
    auditTime: 'Há 2 dias',
    auditDetail: 'Adicionado alerta de horário limite',
  },
  {
    id: 'CDCD-02',
    prefix: 'SM',
    name: 'Supermercados Max',
    score: 91,
    rejections30d: 8,
    avgQueueTime: '3h 15m',
    address: 'Av. das Nações, 8950, Barueri',
    recurrentIssues: [
      {
        title: 'Falta de conferente na descarga',
        description: 'Mercadoria fica parada na expedição aguardando validação visual.',
        icon: 'person_off',
      },
      {
        title: 'Divergência XML vs Físico',
        description: 'Rejeição constante por problemas de arredondamento de ICMS no manifesto.',
        icon: 'text_snippet',
      },
    ],
    auditUser: 'Alex S.',
    auditAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=128',
    auditTime: 'Há 5 dias',
    auditDetail: 'Acordo comercial de tolerância financeira revisado com o distribuidor.',
  },
  {
    id: 'CDCD-03',
    prefix: 'VR',
    name: 'Varejista Regional Sul',
    score: 75,
    rejections30d: 4,
    avgQueueTime: '2h 45m',
    address: 'Rodovia Raposo Tavares, Km 104, Sorocaba',
    recurrentIssues: [
      {
        title: 'Acesso restrito para bi-trem',
        description: 'Balança de entrada suporta no máximo carretas simples de até 3 eixos.',
        icon: 'local_shipping',
      },
    ],
    auditUser: 'Guilherme R.',
    auditAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=128',
    auditTime: 'Ontem',
    auditDetail: 'Restrição física anotada na instrução de frota - bloqueio de tração articulada duplo.',
  },
];
