import { Vehicle, DriverScore, Ctrc, Expense, Ticket, CriticClient, Occurence, DeliveryOccurrence, CurvaAClient, CidadeRota } from './types';

export const initialVehicles: Vehicle[] = [
  {
    id: 'RTA3G45',
    driverName: 'João Silva',
    capacity: '3/4 - 4.5t',
    type: 'Baú Seco',
    status: 'Em Rota',
  },
  {
    id: 'OPR1B22',
    driverName: 'Maria Oliveira',
    capacity: 'Toco - 6t',
    type: 'Refrigerado',
    status: 'Disponível',
  },
  {
    id: 'LOG9H88',
    driverName: 'Não designado',
    capacity: 'VUC - 3t',
    type: 'Baú Seco',
    status: 'Manutenção',
  },
  {
    id: 'FLT8M55',
    driverName: 'Carlos Silva',
    capacity: 'Bitrem - 57t',
    type: 'Sider',
    status: 'Em Rota',
  },
  {
    id: 'TRK4X90',
    driverName: 'Ana Martins',
    capacity: 'VUC - 3.5t',
    type: 'Baú Seco',
    status: 'Disponível',
  },
];

export const initialDrivers: DriverScore[] = [
  {
    id: 'MOT-8842',
    name: 'Carlos Silva',
    score: 94,
    bestRoute: 'São Paulo - Z. Sul',
    status: 'Excelente',
    vehicle: 'Mercedes Sprinter (ABC-1234)',
    avgTime: 14,
    errorRate: 1.2,
    successRate: 98.5,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'MOT-1109',
    name: 'Ana Martins',
    score: 88,
    bestRoute: 'Campinas Exp.',
    status: 'Bom',
    vehicle: 'Volkswagen Delivery (VUC-3344)',
    avgTime: 18,
    errorRate: 1.8,
    successRate: 95.0,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'MOT-2911',
    name: 'Roberto Costa',
    score: 72,
    bestRoute: 'SP - Centro',
    status: 'Regular',
    vehicle: 'Volvo VM 330 (XYZ-9876)',
    avgTime: 23,
    errorRate: 2.5,
    successRate: 91.2,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=256',
  },
  {
    id: 'MOT-5590',
    name: 'Fernando Alves',
    score: 45,
    bestRoute: 'Guarulhos Ind.',
    status: 'Atenção',
    vehicle: 'Scania R450 (ABC-5566)',
    avgTime: 34,
    errorRate: 4.8,
    successRate: 85.4,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
  },
];

export const initialAvailableCtrcs: Ctrc[] = [
  {
    id: 'SPO683890-1',
    destinatario: '28.223.989 RICARD',
    cidade: 'ALFENAS, MG',
    weight: 80.8,
    volume: 5,
    type: 'NORMAL',
    status: 'Disponível',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '25/05/2026',
    remetente: 'FAB.ELASTICOS S',
    ocorrencia: '57 CONFE OK',
    data_ocorr: '22/05/2026',
    nf: '174795',
    valor: 8389.42,
    frete: 340.05,
    unid: 'SPO',
    pagador: 'FAB.ELASTICOS S (REMETENTE)',
    cod: 'C-083890',
    descricao_ocorr: 'CONFERENCIA CONCLUIDA COM SUCESSO',
    data_ocorrencia: '22/05/2026',
    peso_r: 80.8,
    obs: 'Mercadoria frágil - Paletizada',
    disponibilidade: 'DISPONÍVEL',
    localizacao: 'BOX 02 - SETOR NORTE',
  },
  {
    id: 'PPY389007-4',
    destinatario: '64.647.937 ANDRE',
    cidade: 'ALFENAS, MG',
    weight: 23.201,
    volume: 3,
    type: 'NORMAL',
    status: 'Em Rota',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '25/05/2026',
    remetente: 'PROQUALIT TELE',
    ocorrencia: '2 MERC MERC',
    data_ocorr: '22/05/2026',
    nf: '191512',
    valor: 2959.57,
    frete: 76.41,
    unid: 'PPY',
    pagador: '64.647.937 ANDRE (DESTINATÁRIO)',
    cod: 'C-389007',
    descricao_ocorr: 'MERCADORIA EM TRÂNSITO PARA FILIAL',
    data_ocorrencia: '22/05/2026',
    peso_r: 23.201,
    obs: 'Urgente para entrega matinal',
    disponibilidade: 'EM TRÂNSITO',
    localizacao: 'BOX 02 - MEZANINO B',
  },
  {
    id: 'SPO684122-2',
    destinatario: 'A.P. AUTO PECAS E',
    cidade: 'ALFENAS, MG',
    weight: 147.35,
    volume: 13,
    type: 'CURVA A',
    status: 'Transferência',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '26/05/2026',
    remetente: 'FORT LUB PRODI',
    ocorrencia: '69 CHEGA CHEGA',
    data_ocorr: '21/05/2026',
    nf: '1476',
    valor: 7034.12,
    frete: 191.31,
    unid: 'SPO',
    pagador: 'FORT LUB PRODI (REMETENTE)',
    cod: 'C-084122',
    descricao_ocorr: 'MERCADORIA CHEGOU NA FILIAL',
    data_ocorrencia: '21/05/2026',
    peso_r: 147.35,
    obs: 'Atenção ao manuseio - Caixa pesada',
    disponibilidade: 'RESERVADO',
    localizacao: 'BOX 14 - CORREDOR CENTRO',
  },
  {
    id: 'ALF112233-0',
    destinatario: 'AGROFARM VETSH',
    cidade: 'ALFENAS, MG',
    weight: 25,
    volume: 1,
    type: 'NORMAL',
    status: 'Disponível',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '25/05/2026',
    remetente: 'ACESSORIOS DU',
    ocorrencia: '57 CONFE OK',
    data_ocorr: '22/05/2026',
    nf: '11108',
    valor: 632.12,
    frete: 104.46,
    unid: 'ALF',
    pagador: 'AGROFARM VETSH (DESTINATÁRIO)',
    cod: 'C-112233',
    descricao_ocorr: 'CONFERENCIA CONCLUIDA COM SUCESSO',
    data_ocorrencia: '22/05/2026',
    peso_r: 25.0,
    obs: 'Nenhuma observação',
    disponibilidade: 'DISPONÍVEL',
    localizacao: 'BOX 02 - PRATELEIRA A3',
  },
  {
    id: 'SPO685599-9',
    destinatario: 'NATUS FARMA CON',
    cidade: 'ALFENAS, MG',
    weight: 4.98,
    volume: 3,
    type: 'NORMAL',
    status: 'Agendamento',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 99',
    prev_ent: '25/05/2026',
    remetente: 'CREMER S A',
    ocorrencia: '15 ENTRE ENTRE',
    data_ocorr: '20/05/2026',
    nf: '513157',
    valor: 811.67,
    frete: 328.27,
    unid: 'SPO',
    pagador: 'CREMER S A (REMETENTE)',
    cod: 'C-085599',
    descricao_ocorr: 'AGENDAMENTO DE ENTREGA SOLICITADO',
    data_ocorrencia: '20/05/2026',
    peso_r: 4.98,
    obs: 'Agendamento prévio necessário',
    disponibilidade: 'BLOQUEADO',
    localizacao: 'BOX 99 - CHÃO SETOR EXTRA',
  },
  {
    id: 'VAG998877-1',
    destinatario: 'REGINA HELENA BE',
    cidade: 'ALFENAS, MG',
    weight: 6.8,
    volume: 1,
    type: 'NORMAL',
    status: 'Em Rota',
    cidade_ent: 'ALFENAS',
    setor: 'ROTA 02',
    prev_ent: '22/05/2026',
    remetente: 'COMERCIAL FRIG',
    ocorrencia: '2 MERC MERC',
    data_ocorr: '22/05/2026',
    nf: '126125',
    valor: 666.36,
    frete: 71.7,
    unid: 'VAG',
    pagador: 'COMERCIAL FRIG (REMETENTE)',
    cod: 'C-998877',
    descricao_ocorr: 'MERCADORIA EM TRÂNSITO PARA FILIAL',
    data_ocorrencia: '22/05/2026',
    peso_r: 6.8,
    obs: 'Manter refrigerado se aplicável',
    disponibilidade: 'EM TRÂNSITO',
    localizacao: 'BOX 02 - SETOR SUL',
  },
];

// Romaneio page linked CTRCs:
export const initialLinkedCtrcs: Ctrc[] = [
  {
    id: '39281-A',
    destinatario: 'Indústrias Matarazzo',
    cidade: 'São Paulo, SP',
    weight: 1250,
    volume: 3.5,
    type: 'NORMAL',
    status: 'Entregue',
  },
  {
    id: '39282-B',
    destinatario: 'Comercial Silva Ltda',
    cidade: 'Campinas, SP',
    weight: 840,
    volume: 2.1,
    type: 'NORMAL',
    status: 'Entregue',
  },
  {
    id: '39283-C',
    destinatario: 'Distribuidora XYZ',
    cidade: 'Ribeirão Preto, SP',
    weight: 3100,
    volume: 6.2,
    type: 'CURVA A',
    status: 'Recusado',
  },
  {
    id: '39284-D',
    destinatario: 'Armazéns Gerais S.A.',
    cidade: 'Uberlândia, MG',
    weight: 4500,
    volume: 8.5,
    type: 'NORMAL',
    status: 'Pendente',
  },
];

export const initialExpenses: Expense[] = [
  { id: 'exp-1', description: 'Descarga Manual (Cliente B)', value: 150.00 },
  { id: 'exp-2', description: 'Borracharia BR-116', value: 85.50 },
];

export const initialOccurrences: Occurence[] = [
  {
    id: 'occ-1',
    title: 'Cliente Ausente / Recusa',
    time: 'Hoje, 14:30',
    description: 'Relacionado ao CTRC 39283-C. Portaria informou que o responsável não estava.',
    type: 'error',
  },
  {
    id: 'occ-2',
    title: 'Atraso na Carga',
    time: 'Ontem, 08:15',
    description: 'Veículo liberado com 2 horas de atraso no CD Origem devido a sistema inoperante.',
    type: 'neutral',
  },
];

export const initialTickets: Ticket[] = [
  {
    id: '#TRK-99281A',
    title: 'Cliente ausente (3ª tentativa)',
    destinatario: 'João Silva',
    address: 'R. das Flores, 123 - Centro',
    ageMinutes: 15,
    priority: 'Prioridade Alta',
    status: 'Pendente',
    icon: 'error',
  },
  {
    id: '#TRK-77342B',
    title: 'Endereço não localizado',
    destinatario: 'Maria Oliveira',
    address: 'Av. Principal, S/N - Zona Rural',
    ageMinutes: 45,
    status: 'Pendente',
    icon: 'wrong_location',
  },
];

export const initialCriticalClients: CriticClient[] = [
  {
    id: 'CDCD-01',
    prefix: 'CD',
    name: 'Centro Dist. Norte',
    score: 98,
    rejections30d: 12,
    avgQueueTime: '4h 30m',
    address: 'Zona Industrial II, São Paulo',
    recurrentIssues: [
      {
        title: 'Recusa carga após as 16h',
        description: 'Rigidez extrema na janela de recebimento.',
        icon: 'block',
      },
      {
        title: 'Fila de espera excessiva',
        description: 'Média histórica de 4h30m de doca presa.',
        icon: 'hourglass_empty',
      },
    ],
    auditUser: 'Carla M.',
    auditAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=128',
    auditTime: 'Há 2 dias',
    auditDetail: 'Adicionado alerta de horário limite',
  },
  {
    id: 'CDCD-02',
    prefix: 'SM',
    name: 'Supermercados Max',
    score: 91,
    rejections30d: 8,
    avgQueueTime: '3h 15m',
    address: 'Av. das Nações, 8950, Barueri',
    recurrentIssues: [
      {
        title: 'Falta de conferente na descarga',
        description: 'Mercadoria fica parada na expedição aguardando validação visual.',
        icon: 'person_off',
      },
      {
        title: 'Divergência XML vs Físico',
        description: 'Rejeição constante por problemas de arredondamento de ICMS no manifesto.',
        icon: 'text_snippet',
      },
    ],
    auditUser: 'Alex S.',
    auditAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=128',
    auditTime: 'Há 5 dias',
    auditDetail: 'Acordo comercial de tolerância financeira revisado com o distribuidor.',
  },
  {
    id: 'CDCD-03',
    prefix: 'VR',
    name: 'Varejista Regional Sul',
    score: 75,
    rejections30d: 4,
    avgQueueTime: '2h 45m',
    address: 'Rodovia Raposo Tavares, Km 104, Sorocaba',
    recurrentIssues: [
      {
        title: 'Acesso restrito para bi-trem',
        description: 'Balança de entrada suporta no máximo carretas simples de até 3 eixos.',
        icon: 'local_shipping',
      },
    ],
    auditUser: 'Guilherme R.',
    auditAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=128',
    auditTime: 'Ontem',
    auditDetail: 'Restrição física anotada na instrução de frota - bloqueio de tração articulada duplo.',
  },
];

export const initialDeliveryOccurrences: DeliveryOccurrence[] = [
  { codigo: '0', descricao: '0', responsabilidade: 'Transportadora', tipo: 'Em Aberto', setor_ocorr: 'Transferência', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '1', descricao: 'ENTREGA REALIZADA', responsabilidade: 'Informativa', tipo: 'Entrega', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'Finalizadora' },
  { codigo: '2', descricao: 'MERC ENTREGUE-INFORM VIA CELULAR', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'Finalizadora' },
  { codigo: '3', descricao: 'ENTREGA REALIZADA COMPROVANTE RETIDO', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Retidos', retorno_rota: 'Não', tratativa_solucao: 'Finalizadora' },
  { codigo: '4', descricao: 'DESTINATARIO RETIRA', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '6', descricao: 'DESTINAT ALEGA PEDIDO CANCELAD', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '7', descricao: 'AGUARDANDO DESCARREGAMENTO NO DESTINATARIO', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '8', descricao: 'DEST ALEGA MERC DESAC C/PEDIDO', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '9', descricao: 'DESTINAT AUSENTE/FECHADO', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '10', descricao: 'ENDER DESTINAT NAO LOCALIZADO', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '12', descricao: 'ÁREA DE RISCO', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Sim', tratativa_solucao: 'N/A' },
  { codigo: '13', descricao: 'ENTREGA PREJUDICADA P/HORARIO', responsabilidade: 'Transportadora', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Sim', tratativa_solucao: 'N/A' },
  { codigo: '14', descricao: 'AGUARDANDO AGENDAMENTO PELO CLIENTE', responsabilidade: 'Agendamento', tipo: 'Agendamento', setor_ocorr: 'Agendamento', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '15', descricao: 'ENTREGA AGENDADA PELO CLIENTE', responsabilidade: 'Transportadora', tipo: 'Agendamento', setor_ocorr: 'Agendamento', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '17', descricao: 'CONHECIMENTO EMITIDO', responsabilidade: 'Informativa', tipo: 'Mercadoria na Origem', setor_ocorr: 'Transferência', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '18', descricao: 'TROCA DE VOLUME', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '19', descricao: 'ENDERECO ERRADO POR ERRO DE NF', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '20', descricao: 'ENDERECO ERRADO POR ERRO DE DIGITACAO', responsabilidade: 'Transportadora', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '21', descricao: 'RECUSA-CLIENTE INFORMA FALTA DE ESPACO RECEBIMENTO', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '22', descricao: 'RECUSA-APRESENTACAO FORA DA JANELA DE RECEBIMENTO', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Agendamento', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '23', descricao: 'RECUSA-APRESENTADO FORA DO PADRAO DE RECEBIMENTO', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Agendamento', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '24', descricao: 'TRANSP REDESPACHO NAO FAZ A PRACA', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '25', descricao: 'RECUSA NO DESTINO POR AVARIA', responsabilidade: 'Transportadora', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '26', descricao: 'NOTA FISCAL ENTREGUE', responsabilidade: 'Transportadora', tipo: 'Em Aberto', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '27', descricao: 'MERCADORIA NAO ROTEIRIZADA', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '28', descricao: 'ENTREGA COM RESSALVA', responsabilidade: 'Cliente', tipo: 'Pendência Transportadora', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '29', descricao: 'CLIENTE EM RECESSO', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '30', descricao: 'CONTATO AGENDAMENTO REALIZADO C/ CLIENTE', responsabilidade: 'Agendamento', tipo: 'Agendamento', setor_ocorr: 'Agendamento', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '38', descricao: 'RECUSA NO DESTINO POR FALTA DE MERCADORIA', responsabilidade: 'Transportadora', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '39', descricao: 'PENDENCIA DE COLETA', responsabilidade: 'Transportadora', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Sim', tratativa_solucao: 'Abertura' },
  { codigo: '40', descricao: '*BAIXA MANUAL 5S', responsabilidade: 'Informativa', tipo: 'Entrega', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'Finalizadora' },
  { codigo: '44', descricao: 'CARTA DE ISENCAO', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '49', descricao: 'EXTRAVIO DE MERCADORIA', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '50', descricao: 'FALTA DE MERCADORIA', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '51', descricao: 'SOBRA DE MERCADORIA', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '53', descricao: 'MERCADORIA AVARIADA', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '55', descricao: 'CARGA SINISTRADA', responsabilidade: 'Transportadora', tipo: 'Sinistro', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '56', descricao: 'APREENSAO FISCAL', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '57', descricao: 'CONFERENCIA DE PLATAFORMA', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '58', descricao: 'SAIDA DA UNIDADE', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Disponível Transferencia', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '59', descricao: 'CHEGADA NA UNIDADE DESTINO', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '60', descricao: 'SAIDA PARA ENTREGA', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '61', descricao: 'ATRASO DE TRANSFERENCIA', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Transferência', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '62', descricao: 'ATRASO POR VEICULO EM MANUTENCAO / QUEBRA', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '63', descricao: 'VEICULO QUEBRADO (COLETA/ENTREGA)', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Sim', tratativa_solucao: 'N/A' },
  { codigo: '69', descricao: 'CHEGADA NA UNIDADE TRANSBORDO', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Transferência', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '70', descricao: 'AGUARDANDO LIBERACAO COBRANCA', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Cobrança', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '71', descricao: 'MERCADORIA EM PROCESSO DE INDENIZACAO', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '72', descricao: 'DEVOLUÇÃO AUTORIZADA', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'Fechamento' },
  { codigo: '73', descricao: 'ENTREGA DE DEVOLUCAO', responsabilidade: 'Transportadora', tipo: 'Entrega', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Finalizadora' },
  { codigo: '77', descricao: 'TRANSP AGUARD TRATATIVA DO EMBARCADOR', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '78', descricao: 'BECTON DICKINSON - INFORMATIVO DE LACRES', responsabilidade: 'Cliente', tipo: 'Informativo', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '80', descricao: 'MANIFESTACOES / LOCAL COM ACESSO BLOQUEADO', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Disponível', retorno_rota: 'Sim', tratativa_solucao: 'N/A' },
  { codigo: '82', descricao: 'AGENDAMENTO EM TRANSFERENCIA', responsabilidade: 'Cliente', tipo: 'Informativo', setor_ocorr: 'Agendamento', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '85', descricao: 'CONFERIDO COLETA ETIQUETA MANUAL - SEM OCORRENCIA', responsabilidade: 'Cliente', tipo: 'Informativo', setor_ocorr: 'Transferência', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '86', descricao: 'CONFERIDO COLETA ETIQUETA MANUAL - FALTA TOT/PARC', responsabilidade: 'Cliente', tipo: 'Informativo', setor_ocorr: 'Transferência', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '88', descricao: 'NOTIFICACAO DE DEBITO ENVIADA AO SETOR', responsabilidade: 'Informativa', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '90', descricao: 'LIBERADA PELA COBRANCA', responsabilidade: 'Cliente', tipo: 'Em Aberto', setor_ocorr: 'Disponível Cobranca', retorno_rota: 'Não', tratativa_solucao: 'N/A' },
  { codigo: '91', descricao: 'MERCADORIA INDENIZADA', responsabilidade: 'Informativa', tipo: 'Pendência Cliente', setor_ocorr: 'Solução', retorno_rota: 'Não', tratativa_solucao: 'Abertura' },
  { codigo: '93', descricao: 'CTRC EMIT P/EFEITO FRETE/ICMS', responsabilidade: 'Informativa', tipo: 'Pendência Transportadora', setor_ocorr: 'Frete', retorno_rota: 'Não', tratativa_solucao: 'Finalizadora' },
  { codigo: '94', descricao: 'CONHECIMENTO SUBSTITUIDO', responsabilidade: 'Informativa', tipo: 'Pendência Transportadora', setor_ocorr: 'Frete', retorno_rota: 'Não', tratativa_solucao: 'Finalizadora' },
  { codigo: '96', descricao: 'MERCADORIA DEVOLVIDA', responsabilidade: 'Cliente', tipo: 'Pendência Cliente', setor_ocorr: 'Em Rota', retorno_rota: 'Não', tratativa_solucao: 'Fechamento' },
  { codigo: '98', descricao: 'PENDENCIA SOLUCIONADA', responsabilidade: 'Informativa', tipo: 'Em Aberto', setor_ocorr: 'Disponível Pendência', retorno_rota: 'Não', tratativa_solucao: 'Fechamento' },
  { codigo: '999', descricao: 'RECONFERENCIA - COLETOR', responsabilidade: 'Transportadora', tipo: 'Pendência Transportadora', setor_ocorr: 'Disponível', retorno_rota: 'Não', tratativa_solucao: 'N/A' }
];

export const initialCurvaAClients: CurvaAClient[] = [
  { curva_a: 'JJ SOLDAS', cnpj_remetente: '9320155739', cliente_remetente: 'JOAO VIDAL ..' },
  { curva_a: 'ALL NATIONS', cnpj_remetente: '70112000461', cliente_remetente: 'ALL NATIONS COMERCIO EXTERIOR' },
  { curva_a: 'ALL NATIONS', cnpj_remetente: '70112001000', cliente_remetente: 'ALL NATIONS COMERCIO EXTERIOR' },
  { curva_a: 'KNORR BREMSE', cnpj_remetente: '264588000190', cliente_remetente: 'KNORR BREMSE SISTEMAS PARA VEICULOS FERROVIARIOS LTDA' },
  { curva_a: 'KNORR BREMSE', cnpj_remetente: '416170000151', cliente_remetente: 'KNORR BREMSE SISTEMAS P VEICULOS COMERCIAIS BRASIL LTDA' },
  { curva_a: 'HONDA AUTO', cnpj_remetente: '1192333000122', cliente_remetente: 'HONDA AUTOMOVEIS DO BRASIL LTDA' },
  { curva_a: 'HONDA AUTO', cnpj_remetente: '1192333000394', cliente_remetente: 'HONDA AUTOMOVEIS DO BRASIL LTDA' },
  { curva_a: 'RADU', cnpj_remetente: '1361186000843', cliente_remetente: 'RADU INDUSTRIA IMPORTACAO E EX A1' },
  { curva_a: 'RADU', cnpj_remetente: '1361186000843', cliente_remetente: 'RADU INDUSTRIA IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'RADU', cnpj_remetente: '1361186000924', cliente_remetente: 'RADU INDUSTRIA, IMPORTACAO E E' },
  { curva_a: 'RADU', cnpj_remetente: '1361186000924', cliente_remetente: 'RADU INDUSTRIA, IMPORTACAO E E A1' },
  { curva_a: 'ASSA', cnpj_remetente: '2214604000590', cliente_remetente: 'ASSA ABLOY BRASIL INDUSTRIA E COMERCIO LTDA' },
  { curva_a: 'ASSA', cnpj_remetente: '2214604000670', cliente_remetente: 'ASSA ABLOY BRASIL INDUSTRIA E COMERCIO LTDA' },
  { curva_a: 'ART', cnpj_remetente: '2645774000103', cliente_remetente: 'AMALU INDUSTRIA E COMERCIO LTD' },
  { curva_a: 'QUALITRONIX', cnpj_remetente: '2803462000172', cliente_remetente: 'QUALITRONIX TECNOLOGIA LTDA' },
  { curva_a: 'MARELLI', cnpj_remetente: '2865246001476', cliente_remetente: 'MARELLI COFAP DO BRASIL LTDA' },
  { curva_a: 'MARELLI', cnpj_remetente: '2865246002448', cliente_remetente: 'MAGNETI MARELLI COFAP FABR PCS LTDA' },
  { curva_a: 'CEVA', cnpj_remetente: '3229138000155', cliente_remetente: 'CEVA FREIGHT MANAGEMENT DO BRASIL LTDA.' },
  { curva_a: 'CEVA', cnpj_remetente: '3229138002018', cliente_remetente: 'CEVA FREIGHT MANAGEMENT DO BRA' },
  { curva_a: 'PIQUETUR', cnpj_remetente: '4045101000130', cliente_remetente: 'PIQUETUR LOG LOGISTICA E TRANSPORTE LTDA' },
  { curva_a: 'NAKATA', cnpj_remetente: '4156194000412', cliente_remetente: 'NAKATA AUTOMOTIVA' },
  { curva_a: 'GOLDEN DISTRIBUIDORA', cnpj_remetente: '4196935000812', cliente_remetente: 'GOLDEN DISTRIBUIDORA' },
  { curva_a: 'GOLDEN DISTRIBUIDORA', cnpj_remetente: '4196935001207', cliente_remetente: 'GOLDEN DISTRIBUIDORA' },
  { curva_a: 'GOLDEN DISTRIBUIDORA', cnpj_remetente: '4196935002190', cliente_remetente: 'GOLDEN DISTRIBUIDORA' },
  { curva_a: 'HONDA MOTO', cnpj_remetente: '4337168000652', cliente_remetente: 'MOTO HONDA DA AMAZONIA LTDA' },
  { curva_a: 'HONDA MOTO', cnpj_remetente: '4337168001896', cliente_remetente: 'MOTO HONDA DA AMAZONIA LTDA' },
  { curva_a: 'ALPAR', cnpj_remetente: '4896434000172', cliente_remetente: 'ALPAR DO BRASIL INDUSTRIA E COMERCIO DE CALCADOS LTDA' },
  { curva_a: 'ALPAR', cnpj_remetente: '4896434000504', cliente_remetente: 'ALPAR DO BRASIL INDUSTRIA E COMERCIO DE CALCADOS LTDA' },
  { curva_a: 'ZINZANE', cnpj_remetente: '5027195000187', cliente_remetente: 'ZINZANE COMERCIO E CONFECCAO D' },
  { curva_a: 'MUNDIAL', cnpj_remetente: '5075152000177', cliente_remetente: 'MUNDIAL LOGISTICA INTEGRADA LTDA' },
  { curva_a: 'MUNDIAL', cnpj_remetente: '5075152000843', cliente_remetente: 'MUNDIAL LOGISTICA INTEGRADA LTDA' },
  { curva_a: 'MIMO', cnpj_remetente: '5330305000428', cliente_remetente: 'MIMO IMPORTACAO E EXPORTACAO L' },
  { curva_a: 'ATIVA MEDICO', cnpj_remetente: '5359481000140', cliente_remetente: 'CONEXAO MEDICA COMERCIAL LTDA A.' },
  { curva_a: 'RADU', cnpj_remetente: '5627562000183', cliente_remetente: 'INNOVATI BRASIL GROUP LTDA ..' },
  { curva_a: 'COLECAO', cnpj_remetente: '6043130000198', cliente_remetente: 'COLECAO IND COM INFORMATICA E' },
  { curva_a: 'SAE DIGITAL', cnpj_remetente: '6267630001266', cliente_remetente: 'COMPANHIA BRASILEIRA DE EDUCACAO B.' },
  { curva_a: 'SAE DIGITAL', cnpj_remetente: '6267630002157', cliente_remetente: 'COMPANHIA BRASILEIRA DE EDUCAC B.' },
  { curva_a: 'SAE DIGITAL', cnpj_remetente: '6267630002661', cliente_remetente: 'COMPANHIA BRASILEIRA DE EDUCACAO E SISTEMAS DE ENSINO S.A' },
  { curva_a: 'TEXTIL MN', cnpj_remetente: '6311274000269', cliente_remetente: 'TEXTIL MN COMERCIO DE TECIDOS A.' },
  { curva_a: 'TEXTIL MN', cnpj_remetente: '6311274000340', cliente_remetente: 'TEXTIL MN COM TECIDOS A.' },
  { curva_a: 'TEXTIL MN', cnpj_remetente: '6311274000420', cliente_remetente: 'TEXTIL MN COMERCIO DE TECIDOS A.' },
  { curva_a: 'TEXTIL MN', cnpj_remetente: '6311274000692', cliente_remetente: 'TEXTIL MN COMERCIO DE TECIDOS A.' },
  { curva_a: 'TEXTIL MN', cnpj_remetente: '6311274000773', cliente_remetente: 'TEXTIL MN COMERCIO DE TECIDOS A.' },
  { curva_a: 'NEW ERA', cnpj_remetente: '6346545000130', cliente_remetente: 'NEW ERA BRASIL LTDA' },
  { curva_a: 'NOBELPACK', cnpj_remetente: '6905943000140', cliente_remetente: 'NOBELPACK EMBALAGENS E LOGISTICA LTDA' },
  { curva_a: 'NOBELPACK', cnpj_remetente: '6905943000492', cliente_remetente: 'NOBELPACK EMBALAGENS E LOGISTICA LTDA' },
  { curva_a: 'LSLOG', cnpj_remetente: '7259339000156', cliente_remetente: 'LSLOG ARMAZENAGEM E LOGISTICA LTDA.' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517000107', cliente_remetente: 'SIMPRESS COM LOCACAO SERVICOS' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517000360', cliente_remetente: 'SIMPRESS COM LOCACAO SERVICOS' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517000794', cliente_remetente: 'SIMPRESS COM LOC E SERV LTDA' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517001090', cliente_remetente: 'SIMPRESS COM LOCACAO SERVICOS' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517001170', cliente_remetente: 'SIMPRESS COM LOC E SERVICOS' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517001251', cliente_remetente: 'SIMPRESS COM LOCACAO SERVICOS' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517001413', cliente_remetente: 'SIMPRESS COMERCIO LOCACAO E SERVICOS LTDA' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517001502', cliente_remetente: 'SIMPRESS COM LOCACAO SERVICOS' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517001766', cliente_remetente: 'SIMPRESS COMERCIO LOCACAO E SERVICOS LTDA' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '7432517001847', cliente_remetente: 'SIMPRESS COMERCIO LOCACAO E SERVICOS LTDA' },
  { curva_a: 'SIMPRESS', cnpj_remetente: '743251705249', cliente_remetente: 'SIMPRESS COMERCIO LOCACAO E SERVICOS LTDA' },
  { curva_a: 'VIDA FORTE', cnpj_remetente: '7455576000192', cliente_remetente: 'VIDA FORTE NUTRIE' },
  { curva_a: 'VIDA FORTE', cnpj_remetente: '7455576000940', cliente_remetente: 'VIDA FORTE NUTRIENTES INDUSTRIA E COMERCIO DE PRODUTOS NATUR' },
  { curva_a: 'POSTALL', cnpj_remetente: '7471771000106', cliente_remetente: 'POSTALL TRANSPORTE ARMAZENAGEM' },
  { curva_a: 'POSTALL', cnpj_remetente: '7471771000378', cliente_remetente: 'POSTALL TRANSPORTE ARMAZENAGEM' },
  { curva_a: 'POSTALL', cnpj_remetente: '7471771000459', cliente_remetente: 'POSTALL TRANSPORTE ARMAZENAGEM' },
  { curva_a: 'POSTALL', cnpj_remetente: '7471771000530', cliente_remetente: 'POSTALL TRANSPORTE ARMAZENAGEM' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '7597505000124', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'PMI SOUTH', cnpj_remetente: '8211330000219', cliente_remetente: 'PMI SOUTH AMERICA INDUSTRIA DE PLASTICO LTDA' },
  { curva_a: 'SK', cnpj_remetente: '8237002000453', cliente_remetente: 'S K AUTOMOTIVE DIST AUTOPECAS' },
  { curva_a: 'SK', cnpj_remetente: '8237002003479', cliente_remetente: 'SK AUTOMOTIVE DISTRIBUIDORA DE AUTOPECAS LTDA' },
  { curva_a: 'SK', cnpj_remetente: '8237002005501', cliente_remetente: 'SK AUTOMOTIVE DISTRIBUIDORA DE AUTOPECAS LTDA' },
  { curva_a: 'SK', cnpj_remetente: '8237002006060', cliente_remetente: 'SK AUTOMOTIVE DISTRIBUIDORA DE' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '8435684000328', cliente_remetente: 'EMBREPAR AUTOMOTIVA LTDA' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '8623848000260', cliente_remetente: 'SOLUCOES MODERNA EDITORA' },
  { curva_a: 'RADU', cnpj_remetente: '8956394000168', cliente_remetente: 'BAG-ONLINE COMERCIO DE BOLSAS LT .1' },
  { curva_a: 'RADU', cnpj_remetente: '8956394000915', cliente_remetente: 'BAG-ONLINE COMERCIO DE BOLSAS LT ..' },
  { curva_a: 'FARMA VISION', cnpj_remetente: '9058502000148', cliente_remetente: 'FARMA VISION IMPORTACAO E EXPO A.' },
  { curva_a: 'FARMA VISION', cnpj_remetente: '9058502000300', cliente_remetente: 'FARMA VISION IMPORTACAO E EXPO A.' },
  { curva_a: 'ATIVA MEDICO', cnpj_remetente: '9182725000112', cliente_remetente: 'ATIVA MEDICO CIRURGICA LTDA A.' },
  { curva_a: 'ATIVA MEDICO', cnpj_remetente: '9182725000201', cliente_remetente: 'ATIVA MEDICO CIRURGICA LTDA A.' },
  { curva_a: 'CREMER', cnpj_remetente: '10339739000186', cliente_remetente: 'FW INDUSTRIA E COMERCIO DE PRODUTOS DE HIGIENE S.A.' },
  { curva_a: 'PILLOWTEX', cnpj_remetente: '10445925000108', cliente_remetente: 'PILLOWTEX INDUSTRIA E COMERCIO TEXTIL LTDA' },
  { curva_a: 'PILLOWTEX', cnpj_remetente: '10445925000280', cliente_remetente: 'PILLOWTEX IND E COM TEXTIL' },
  { curva_a: 'COLECAO', cnpj_remetente: '10590774000254', cliente_remetente: 'COLEPACK INDUSTRIA E COMERCIO DE EMBALAGENS EIRELI' },
  { curva_a: 'COLECAO', cnpj_remetente: '10590774000335', cliente_remetente: 'COLEPACK INDUSTRIA E COMERCIO' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '10619557000169', cliente_remetente: 'PTD COMERCIO DE PECAS EIRELI' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '10628017000141', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'PIMPOLHO', cnpj_remetente: '10912561000382', cliente_remetente: 'PIMPOLHO PRODUTOS INFANTIS LTD' },
  { curva_a: 'BYWER', cnpj_remetente: '11303619000191', cliente_remetente: 'BYWER INDUSTRIA DE PLASTICOS L' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '11861148000137', cliente_remetente: 'R.M.C COMERCIO DE ROUPAS E ARTIG ..' },
  { curva_a: 'CREMER', cnpj_remetente: '12420164003504', cliente_remetente: 'CM HOSPITALAR SA' },
  { curva_a: 'RADU', cnpj_remetente: '12420925000170', cliente_remetente: 'BAG - FRANQUIAS LTDA ..' },
  { curva_a: 'JJ SOLDAS', cnpj_remetente: '13332103000109', cliente_remetente: 'JJ SOLDAS FERRAMENTAS E EQUIPA B.' },
  { curva_a: 'JJ SOLDAS', cnpj_remetente: '13332103000281', cliente_remetente: 'JJ SOLDAS FERRAMENTAS E EQUIPA B.' },
  { curva_a: 'JJ SOLDAS', cnpj_remetente: '13332103000362', cliente_remetente: 'JJ SOLDAS FERRAMENTAS E EQUIPA ..' },
  { curva_a: 'RADU', cnpj_remetente: '13638810000110', cliente_remetente: 'R E N ARTEFATOS DE COURO LTDA A.' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '14158418000136', cliente_remetente: 'SANTILLANA EDUCACAO LTDA ' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '14158418000217', cliente_remetente: 'SANTILLANA EDUCACAO LTDA' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '14158418001370', cliente_remetente: 'SANTILLANA EDUCACAO LTDA' },
  { curva_a: 'MUNDO DAS FERRAMENTAS', cnpj_remetente: '14444564000128', cliente_remetente: 'MUNDO DAS FERRAMENTAS DO BRASIL LTDA' },
  { curva_a: 'ATIVA MEDICO', cnpj_remetente: '14792179000171', cliente_remetente: 'SUPRA SUPRIMENTO INF ESCR LTDA A.' },
  { curva_a: 'RADU', cnpj_remetente: '15204730000181', cliente_remetente: 'MINAS BAG ARTEFATOS DE COURO EIR ..' },
  { curva_a: 'RADU', cnpj_remetente: '15204764000176', cliente_remetente: 'ESTACAO BAG ARTEFATOS DE COURO L ..' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '15487295000140', cliente_remetente: 'HGD ARMAZEM GERAL LTDA' },
  { curva_a: 'MKT LOG LOGISTICA', cnpj_remetente: '15769911000155', cliente_remetente: 'MKT LOG LOGISTICA' },
  { curva_a: 'CEDRO', cnpj_remetente: '17245234000100', cliente_remetente: 'CIA DE FIACAO E TECIDOS C (..)' },
  { curva_a: 'CEDRO', cnpj_remetente: '17245234000363', cliente_remetente: 'CIA DE FIACAO E TECIDOS C (..)' },
  { curva_a: 'CEDRO', cnpj_remetente: '17245234000525', cliente_remetente: 'CIA DE FIACAO E TECIDOS C (..)' },
  { curva_a: 'CEDRO', cnpj_remetente: '17245234002730', cliente_remetente: 'CIA DE FIACAO E TECIDOS CEDRO A.' },
  { curva_a: 'CEDRO', cnpj_remetente: '17245234003974', cliente_remetente: 'CIA DE FIACAO E TECIDOS C (..)' },
  { curva_a: 'RADU', cnpj_remetente: '17267747000375', cliente_remetente: 'TIKOR COMERCIO DE BOLSAS E ACESS ..' },
  { curva_a: 'RADU', cnpj_remetente: '17364082000156', cliente_remetente: 'ES BAG ARTEFATOS DE COURO LTDA ..' },
  { curva_a: 'GRN', cnpj_remetente: '17543669000122', cliente_remetente: 'LANTO TRANSPORTES LTDA ..' },
  { curva_a: 'GRN', cnpj_remetente: '17543669000203', cliente_remetente: 'LANTO TRANSPORTES LTDA ..' },
  { curva_a: 'GRN', cnpj_remetente: '17543669000394', cliente_remetente: 'LANTO TRANSPORTES LTDA ..' },
  { curva_a: 'PHL', cnpj_remetente: '17838120000165', cliente_remetente: 'PHL SOLUCOES LOGISTICA LTDA' },
  { curva_a: 'INDEPENDENCE', cnpj_remetente: '18136504000107', cliente_remetente: 'INDEPENDENCE COMERCIO E IMPORT' },
  { curva_a: 'BELFAR', cnpj_remetente: '18324343000177', cliente_remetente: 'BELFAR LTDA' },
  { curva_a: 'BELFAR', cnpj_remetente: '18324343000509', cliente_remetente: 'BELFAR LTDA(MATOZINHOS)' },
  { curva_a: 'BELFAR', cnpj_remetente: '18324343000762', cliente_remetente: 'BELFAR LTDA' },
  { curva_a: 'RADU', cnpj_remetente: '18343177000156', cliente_remetente: 'MARE ARTIGOS DE VIAGENS COMERCIO ..' },
  { curva_a: 'RADU', cnpj_remetente: '19256834000190', cliente_remetente: 'CABO FRIO BAG ARTIGOS DE COURO L ..' },
  { curva_a: 'RADU', cnpj_remetente: '19256834000271', cliente_remetente: 'CABO FRIO BAG ARTIGOS DE COURO L ..' },
  { curva_a: 'COMPANHIA INDUSTRIAL CATAGUASES', cnpj_remetente: '19526748000150', cliente_remetente: 'COMPANHIA INDUSTRIAL CATAGUASES B.' },
  { curva_a: 'COMPANHIA INDUSTRIAL CATAGUASES', cnpj_remetente: '19526748000665', cliente_remetente: 'COMPANHIA INDUSTRIAL CATAGUASES ..' },
  { curva_a: 'COMPANHIA INDUSTRIAL CATAGUASES', cnpj_remetente: '19526748001203', cliente_remetente: 'COMPANHIA INDUSTRIAL CATAGUASES B.' },
  { curva_a: 'COMPANHIA INDUSTRIAL CATAGUASES', cnpj_remetente: '19526748001394', cliente_remetente: 'COMPANHIA INDUSTRIAL CATAGUASES B.' },
  { curva_a: 'MARLUVAS', cnpj_remetente: '19653054000184', cliente_remetente: 'MARLUVAS CALCADOS DE SEGURANCA' },
  { curva_a: 'MARLUVAS', cnpj_remetente: '19653054002047', cliente_remetente: 'MARLUVAS EQUIPAMENTOS DE SEGUR' },
  { curva_a: 'MARLUVAS', cnpj_remetente: '19653054002713', cliente_remetente: 'MARLUVAS EQUIPAMENTOS DE SEGURANCA LTDA' },
  { curva_a: 'MARLUVAS', cnpj_remetente: '19653054002802', cliente_remetente: 'MARLUVAS EQUIPAMENTOS DE SEGURAN' },
  { curva_a: 'MARLUVAS', cnpj_remetente: '19653054003604', cliente_remetente: 'MARLUVAS EQUIPAMENTOS DE SEGUR' },
  { curva_a: 'SÃO GERALDO', cnpj_remetente: '19791227000120', cliente_remetente: 'FIACAO E TECELAGEM SAO GERALDO' },
  { curva_a: 'ESTAMPARIA', cnpj_remetente: '19791987000138', cliente_remetente: 'ESTAMPARIA SA' },
  { curva_a: 'RADU', cnpj_remetente: '20646946000137', cliente_remetente: 'J B COMERCIO VAREJISTA DE ARTIGO ..' },
  { curva_a: 'RADU', cnpj_remetente: '21589623000111', cliente_remetente: 'MACAE BAG ARTIGOS DE COURO EIREL ..' },
  { curva_a: 'RADU', cnpj_remetente: '21589623000464', cliente_remetente: 'MACAE BAG ARTIGOS DE COURO LTDA ..' },
  { curva_a: 'BYWER', cnpj_remetente: '21767359000169', cliente_remetente: 'TINGUI DISTRIBUIDORA LTDA' },
  { curva_a: 'SIGNIFY', cnpj_remetente: '22555787000352', cliente_remetente: 'SIGNIFY ILUMINACAO BRASIL LTDA' },
  { curva_a: 'SIGNIFY', cnpj_remetente: '22555787000433', cliente_remetente: 'SIGNIFY ILUMINACAO BRASIL LTDA.' },
  { curva_a: 'GRN', cnpj_remetente: '22959648000122', cliente_remetente: 'GRN TRANSPORTES LTDA ..' },
  { curva_a: 'GRN', cnpj_remetente: '22959648000203', cliente_remetente: 'GRN TRANSPORTES LTDA ..' },
  { curva_a: 'RADU', cnpj_remetente: '24297112000114', cliente_remetente: 'ARARUAMA BAG ARTIGOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '24297112000203', cliente_remetente: 'ARARUAMA BAG ARTIGOS DE COURO LT ..' },
  { curva_a: 'PHINIA', cnpj_remetente: '25043386000140', cliente_remetente: 'PHINIA DELPHI BRASIL LTDA' },
  { curva_a: 'PHINIA', cnpj_remetente: '25043386000301', cliente_remetente: 'PHINIA DELPHI BRASIL LTDA' },
  { curva_a: 'SAE DIGITAL', cnpj_remetente: '25174365000244', cliente_remetente: 'SAE DIGITAL AS' },
  { curva_a: 'CEDRO', cnpj_remetente: '25582727000155', cliente_remetente: 'COMPANHIA DE FIACAO E TECIDOS SANTO ANTONIO' },
  { curva_a: 'CEDRO', cnpj_remetente: '25582727000740', cliente_remetente: 'COMPANHIA DE FIACAO E TECIDOS SANTO ANTONIO' },
  { curva_a: 'REAL MOTO', cnpj_remetente: '25630302001812', cliente_remetente: 'REAL MOTO PECAS LTDA' },
  { curva_a: 'REAL MOTO', cnpj_remetente: '25630302002541', cliente_remetente: 'REAL MOTO PECAS LTDA' },
  { curva_a: 'RADU', cnpj_remetente: '26632462000115', cliente_remetente: 'TOPBAG ARTEFATOS DE VIAGEM LTDA ..' },
  { curva_a: 'RADU', cnpj_remetente: '26632462000204', cliente_remetente: 'TOPBAG ARTEFATOS DE VIAGEM LTDA ..' },
  { curva_a: 'RADU', cnpj_remetente: '26887488000104', cliente_remetente: 'STEAL BAG ARTIGOS DE VIAGENS COM ..' },
  { curva_a: 'RADU', cnpj_remetente: '27097144000164', cliente_remetente: 'CATETE BAG COMERCIO LTDA ..' },
  { curva_a: 'RADU', cnpj_remetente: '27097144000245', cliente_remetente: 'CATETE BAG COMERCIO LTDA ..' },
  { curva_a: 'PIMPOLHO', cnpj_remetente: '28053601000181', cliente_remetente: 'BRITO E CIA LTDA' },
  { curva_a: 'INDEPENDENCE', cnpj_remetente: '28368254000186', cliente_remetente: 'MATCON COMERCIAL LTDA' },
  { curva_a: 'RADU', cnpj_remetente: '28778369000149', cliente_remetente: 'SVS BAG ARTIGOS DE VIAGENS COMER ..' },
  { curva_a: 'RADU', cnpj_remetente: '28964978000192', cliente_remetente: 'SANPEX COMERCIO DE ARTIGOS DE VI A.' },
  { curva_a: 'PMI SOUTH', cnpj_remetente: '30055933000651', cliente_remetente: 'PMI SOUTH AMERICA INDUSTRIA DE PLASTICO LTDA' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '30126886000185', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'RADU', cnpj_remetente: '31355436000127', cliente_remetente: 'MJ ARTEFATOS DE COURO LTDA A.' },
  { curva_a: 'Mercedes Carros e Vans', cnpj_remetente: '31715616000504', cliente_remetente: 'MERCEDES BENZ CARS E VANS BRASIL LTDA' },
  { curva_a: 'ART', cnpj_remetente: '31908825000132', cliente_remetente: 'ART LATEX IND E COM DE ARTEFATOS DE LATEX LTDA' },
  { curva_a: 'ART', cnpj_remetente: '31908825000213', cliente_remetente: 'ART LATEX IND E COM DE ARTEFATOS DE LATEX LTDA' },
  { curva_a: 'ART', cnpj_remetente: '31908825000485', cliente_remetente: 'ART LATEX IND E COM DE ARTEFATOS DE LATEX LTDA' },
  { curva_a: 'PILLOWTEX', cnpj_remetente: '32111654000189', cliente_remetente: 'PILLOWTEX COLCHOES INDUSTRIA E' },
  { curva_a: 'RADU', cnpj_remetente: '32125532000141', cliente_remetente: 'R HOSKEN FRAUCHES ARTEFATOS DE C ..' },
  { curva_a: 'RADU', cnpj_remetente: '32223340000178', cliente_remetente: 'VIA BAG ARTIGOS DE VIAGENS COMER ..' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '32259357000185', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '32263479000145', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'RADU', cnpj_remetente: '33035098000848', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098001062', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098001143', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098001224', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098001577', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098001739', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098001909', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098002034', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098002620', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098002700', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098002891', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098003359', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098003430', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO A.' },
  { curva_a: 'RADU', cnpj_remetente: '33035098003782', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33035098004401', cliente_remetente: 'A ORIGINAL ARTEFATOS DE COURO LT ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246000127', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246000208', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246000470', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246000631', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246000712', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246000984', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001018', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001107', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001280', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001360', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001441', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001522', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001603', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001875', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246001956', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002090', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002251', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE .1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002332', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002413', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002502', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002766', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002847', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246002928', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246003142', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246003223', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246003495', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246003576', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246003738', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246003819', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246003908', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004114', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004203', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004386', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004467', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004548', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004629', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004700', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246004890', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005005', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005196', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005277', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005358', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005439', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005510', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005609', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005781', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246005862', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006168', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006249', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006320', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006400', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS D A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006591', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006672', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS D A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006753', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246006915', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007059', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007130', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007210', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007300', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007482', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007644', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007806', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246007997', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246008101', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246008373', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246008454', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246008616', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246008705', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE .1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246009000', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246009183', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246009426', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246009507', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246009698', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246009850', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246009930', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246010009', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246010190', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246010270', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246010351', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246010432', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246010513', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246011080', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE .1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246011161', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246011323', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246011404', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246011595', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246011676', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246011919', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246012052', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246012486', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246012729', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246013024', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246013105', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'RADU', cnpj_remetente: '33050246013539', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246013610', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246013881', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246013962', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246014004', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246014187', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A.' },
  { curva_a: 'RADU', cnpj_remetente: '33050246014268', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE A1' },
  { curva_a: 'RADU', cnpj_remetente: '33050246014420', cliente_remetente: 'SHEHRAZADE MODAS E ARTEFATOS DE ..' },
  { curva_a: 'ABB', cnpj_remetente: '33449965000115', cliente_remetente: 'ABB AUTOMACAO LTDA' },
  { curva_a: 'ABB', cnpj_remetente: '33449988000120', cliente_remetente: 'ABB ELETRIFICACAO LTDA' },
  { curva_a: 'CORTTEX', cnpj_remetente: '34244135000114', cliente_remetente: 'FATEX INDUSTRIAL, COMERCIAL, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'CORTTEX', cnpj_remetente: '34244135000203', cliente_remetente: 'FATEX INDUSTRIAL, COMERCIAL, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'CORTTEX', cnpj_remetente: '34244135000386', cliente_remetente: 'FATEX INDUSTRIAL, COMERCIAL, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'CORTTEX', cnpj_remetente: '34244135000548', cliente_remetente: 'FATEX INDUSTRIAL, COMERCIAL, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '35943604000156', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA D A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '35943604000407', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE ..' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '35943604000580', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA D' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '35943604000580', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA D A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360401470', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360401985', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE ..' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360402019', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360402108', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360402604', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360402876', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360403090', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360403503', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360403767', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE ..' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360404909', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360405620', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360406197', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360407088', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE ..' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360408211', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360408645', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360408998', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360409102', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360409293', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360409374', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360409455', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA D A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360409455', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE ARTIGOS ESPORTIVOS S A' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360409706', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360410038', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE ..' },
  { curva_a: 'TERRAS DE AVENTURA', cnpj_remetente: '3594360410119', cliente_remetente: 'TERRAS DE AVENTURA INDUSTRIA DE A.' },
  { curva_a: 'FARMA VISION', cnpj_remetente: '37407347000163', cliente_remetente: 'NEWARIS LIFESCIENCES LTDA A.' },
  { curva_a: 'JJ SOLDAS', cnpj_remetente: '39968082000106', cliente_remetente: 'JJ MAQUINAS COMERCIO E SERVICOS ..' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '40505191000168', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'RADU', cnpj_remetente: '41750987000149', cliente_remetente: 'BAG LOG SOLUCOES DE TRANSPORTE E ..' },
  { curva_a: 'RADU', cnpj_remetente: '42030457000199', cliente_remetente: 'BAG IMPERIAL MODAS E ARTEFATOS D ..' },
  { curva_a: 'RADU', cnpj_remetente: '42030584000198', cliente_remetente: 'BAG MERCADAO MODAS E ARTEFATOS D ..' },
  { curva_a: 'GALZERANO', cnpj_remetente: '43594977000197', cliente_remetente: 'GALZERANO INDUSTRIA DE CARRINH' },
  { curva_a: 'GALZERANO', cnpj_remetente: '43594977000278', cliente_remetente: 'GALZERANO INDUSTRIA DE CARRINHOS E BERCOS LTDA' },
  { curva_a: 'CAMESA', cnpj_remetente: '43672716000148', cliente_remetente: 'CAMESA INDUSTRIA TEXTIL LTDA' },
  { curva_a: 'CAMESA', cnpj_remetente: '43672716000300', cliente_remetente: 'CAMESA IND. TEXTIL LTDA' },
  { curva_a: 'CAMESA', cnpj_remetente: '43672716000490', cliente_remetente: 'CAMESA IND TEXTIL LTDA' },
  { curva_a: 'CAMESA', cnpj_remetente: '43672716000652', cliente_remetente: 'CAMESA INDUSTRIA TEXTIL LTDA' },
  { curva_a: 'CAMESA', cnpj_remetente: '43672716000814', cliente_remetente: 'CAMESA INDUSTRIA TEXTIL L (..)' },
  { curva_a: 'CEVA', cnpj_remetente: '43854116005089', cliente_remetente: 'CEVA LOGISTICS LTDA' },
  { curva_a: 'CEVA', cnpj_remetente: '43854116006484', cliente_remetente: 'CEVA LOGISTICS LTDA' },
  { curva_a: 'CEVA', cnpj_remetente: '43854116006727', cliente_remetente: 'CEVA LOGISTICS LTDA' },
  { curva_a: 'CEVA', cnpj_remetente: '43854116008851', cliente_remetente: 'CEVA LOGISTICS LTDA' },
  { curva_a: 'CASA PUBLICADORA', cnpj_remetente: '44194660000126', cliente_remetente: 'CASA PUBLICADORA BRASILEIRA' },
  { curva_a: 'ADERE', cnpj_remetente: '46062030000123', cliente_remetente: 'ADERE PRODUTOS AUTO ADESIVOS L' },
  { curva_a: 'KARCHER', cnpj_remetente: '47110960000178', cliente_remetente: 'KARCHER INDUSTRIA E COMERCIO LIMITADA' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '47519158000136', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'NOBELPACK', cnpj_remetente: '47577531000105', cliente_remetente: 'NOBELPLAST EMBALAGENS EIRELI' },
  { curva_a: 'CORTTEX', cnpj_remetente: '48606503000131', cliente_remetente: 'CORTTEX INDUSTRIA, COMERCIO, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'CORTTEX', cnpj_remetente: '48606503000484', cliente_remetente: 'CORTTEX INDUSTRIA, COMERCIO, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'CORTTEX', cnpj_remetente: '48606503000565', cliente_remetente: 'CORTTEX INDUSTRIA, COMERCIO, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'CORTTEX', cnpj_remetente: '48606503000646', cliente_remetente: 'CORTTEX INDUSTRIA, COMERCIO, IMPORTACAO E EXPORTACAO LTDA' },
  { curva_a: 'RADU', cnpj_remetente: '48898502000108', cliente_remetente: 'VITORIA MALAS ACESSORIOS E ARTEF A1' },
  { curva_a: 'RADU', cnpj_remetente: '48929737000110', cliente_remetente: 'PRAIA DA COSTA ACESSORIOS LTDA A1' },
  { curva_a: 'RADU', cnpj_remetente: '48929737000209', cliente_remetente: 'PRAIA DA COSTA ACESSORIOS LTDA A.' },
  { curva_a: 'ENERGIZER', cnpj_remetente: '49032964000704', cliente_remetente: 'ENERGIZER BRASIL INDUSTRIA E COMERCIO DE BENS DE CONSUMO LTD' },
  { curva_a: 'ADVANCE', cnpj_remetente: '49311558000187', cliente_remetente: 'ADVANCE INDUSTRIA TEXTIL LTDA' },
  { curva_a: 'GRN', cnpj_remetente: '51493584000204', cliente_remetente: 'LTO LOGISTICA E TRANSPORTES LTDA ..' },
  { curva_a: 'RADU', cnpj_remetente: '52443513000170', cliente_remetente: 'MESTRE ALVARO LUGGAGE E ACESSORI A1' },
  { curva_a: 'BLACK E DECKER', cnpj_remetente: '53296273000191', cliente_remetente: 'BLACK E DECKER DO BRASIL LTDA' },
  { curva_a: 'BLACK E DECKER', cnpj_remetente: '53296273003298', cliente_remetente: 'BLACK E DECKER DO BRASIL LTDA' },
  { curva_a: 'PHL', cnpj_remetente: '53520885000116', cliente_remetente: 'PHL EXPRESS TRANSPORTES LTDA' },
  { curva_a: 'GRN', cnpj_remetente: '54672344000176', cliente_remetente: 'ARGON TRANSPORTES DE CARGAS LTDA A.' },
  { curva_a: 'GRN', cnpj_remetente: '54672344000257', cliente_remetente: 'ARGON TRANSPORTES DE CARGAS LTDA A.' },
  { curva_a: 'RADU', cnpj_remetente: '55145368000130', cliente_remetente: 'MAG WEST SP ACESSORIOS LTDA ..' },
  { curva_a: 'RADU', cnpj_remetente: '55145402000176', cliente_remetente: 'MAG BOURBON SP PRESENTES LTDA A1' },
  { curva_a: 'Mercedes Campo Largo', cnpj_remetente: '55377642000104', cliente_remetente: 'MERCEDES BENZ DO BRASIL LTDA' },
  { curva_a: 'Mercedes Campo Largo', cnpj_remetente: '55377642000791', cliente_remetente: 'CAMPO LARGO COMERCIO DE VEICULOS E PECAS LTDA' },
  { curva_a: 'RADU', cnpj_remetente: '55408081000155', cliente_remetente: 'J SETE LAGOAS COMERCIO LTDA A.' },
  { curva_a: 'RADU', cnpj_remetente: '55649951000269', cliente_remetente: 'SB BOA VISTA MS PRESENTES LTDA A1' },
  { curva_a: 'RADU', cnpj_remetente: '55651288000156', cliente_remetente: 'IM INTER GRU COMERCIO DE MALAS L A1' },
  { curva_a: 'RADU', cnpj_remetente: '55670585000149', cliente_remetente: 'JD PRUDEN VAREJO LTDA A.' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057001003', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS LTDA' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057001194', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS LTDA' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057001275', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS LTDA' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057001356', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS LTDA' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057002085', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS LTDA' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057002247', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057002328', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS LTDA' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '55847057002409', cliente_remetente: 'FORT LUB PRODUTOS AUTOMOTIVOS LTDA' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '57630110000154', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '57652261000103', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'CEBOLA BRINDES', cnpj_remetente: '57655941000180', cliente_remetente: 'CEBOLA BRINDES' },
  { curva_a: 'Mercedes Trucks e Bus', cnpj_remetente: '59104273001443', cliente_remetente: 'MERCEDES BENZ DO BRASIL LTDA' },
  { curva_a: 'Mercedes Trucks e Bus', cnpj_remetente: '59104273002415', cliente_remetente: 'MERCEDES BENZ DO BRASIL LTDA' },
  { curva_a: 'GM', cnpj_remetente: '59275792002799', cliente_remetente: 'GENERAL MOTORS DO BRASIL' },
  { curva_a: 'MULTILASER', cnpj_remetente: '59717553000617', cliente_remetente: 'MULTILASER INDUSTRIAL S.A' },
  { curva_a: 'BEL MICRO', cnpj_remetente: '60395190000115', cliente_remetente: 'BEL LOG ARMAZEM GERAL LTD (A1)' },
  { curva_a: 'COATS', cnpj_remetente: '61148052000102', cliente_remetente: 'COATS CORRENTE LTDA ..' },
  { curva_a: 'COATS', cnpj_remetente: '61148052001761', cliente_remetente: 'COATS CORRENTE LTDA A.' },
  { curva_a: 'COATS', cnpj_remetente: '61148052001842', cliente_remetente: 'COATS CORRENTE LTDA ..' },
  { curva_a: 'COATS', cnpj_remetente: '61148052002300', cliente_remetente: 'COATS CORRENTE LTDA. .3' },
  { curva_a: 'CIRURGICA', cnpj_remetente: '61418042000131', cliente_remetente: 'CIRURGICA FERNANDES' },
  { curva_a: 'SANTISTA', cnpj_remetente: '61520607000197', cliente_remetente: 'SANTISTA TEXTIL S.A.' },
  { curva_a: 'SANTISTA', cnpj_remetente: '61520607001835', cliente_remetente: 'SANTISTA TEXTIL S.A.' },
  { curva_a: 'SANTISTA', cnpj_remetente: '61520607001916', cliente_remetente: 'SANTISTA TEXTIL S.A.' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '62136304000138', cliente_remetente: 'EDITORA MODERNA LTDA' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '62136304001100', cliente_remetente: 'EDITORA MODERNA LTDA' },
  { curva_a: 'EDITORA MODERNA', cnpj_remetente: '62136304003820', cliente_remetente: 'EDITORA MODERNA LTDA' },
  { curva_a: 'ANCORA', cnpj_remetente: '67647412000199', cliente_remetente: 'ANCORA GROUP LTDA' },
  { curva_a: 'ANCORA', cnpj_remetente: '67647412000350', cliente_remetente: 'ANCORA GROUP LTDA' },
  { curva_a: 'ANCORA', cnpj_remetente: '67647412000431', cliente_remetente: 'ANCORA GROUP LTDA' },
  { curva_a: 'PROQUALIT', cnpj_remetente: '68389097000371', cliente_remetente: 'PROQUALIT TELECOM LTDA' },
  { curva_a: 'PROQUALIT', cnpj_remetente: '68389097000967', cliente_remetente: 'PROQUALIT TELECOM LTDA.' },
  { curva_a: 'BEL MICRO', cnpj_remetente: '71052559000103', cliente_remetente: 'BEL MICRO TECNOLOGIA SA' },
  { curva_a: 'BEL MICRO', cnpj_remetente: '71052559000375', cliente_remetente: 'BEL MICRO TECNOLOGIA SA' },
  { curva_a: 'BEL MICRO', cnpj_remetente: '71052559000456', cliente_remetente: 'BEL MICRO TECNOLOGIA SA' },
  { curva_a: 'BEL MICRO', cnpj_remetente: '71052559000537', cliente_remetente: 'BEL MICRO TECNOLOGIA SA' },
  { curva_a: 'BEL MICRO', cnpj_remetente: '71052559000707', cliente_remetente: 'BEL MICRO TECNOLOGIA SA' },
  { curva_a: 'BEL MICRO', cnpj_remetente: '7105255901770', cliente_remetente: 'BEL MICRO TECNOLOGIA SA' },
  { curva_a: 'PRATI', cnpj_remetente: '73856593001057', cliente_remetente: 'PRATI DONADUZZI CIA LTDA' },
  { curva_a: 'EMBREPAR', cnpj_remetente: '75592006001176', cliente_remetente: 'EMBREPAR DISTRIBUIDORA DE PECA' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325000118', cliente_remetente: 'CREMER SA' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325001351', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325001866', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325002080', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325002161', cliente_remetente: 'CREMER S A' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325002242', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325003648', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325004377', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325004458', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325004610', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325005004', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325005187', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325005268', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'CREMER', cnpj_remetente: '82641325005349', cliente_remetente: 'CREMER S.A.' },
  { curva_a: 'NAKATA', cnpj_remetente: '88610126000471', cliente_remetente: 'FRASLE SA' },
  { curva_a: 'NAKATA', cnpj_remetente: '88610126001796', cliente_remetente: 'FRASLE SA' },
  { curva_a: 'NAKATA', cnpj_remetente: '90492695000401', cliente_remetente: 'FREIOS CONTROIL LTDA' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406000208', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406000461', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406000542', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406000895', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406001190', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406001352', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406001867', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406002324', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406002596', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406002758', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406003215', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406003487', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406004025', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406004297', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406004378', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406004459', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406004530', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406004610', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406005005', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406005188', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406005269', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT .2' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406005692', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'FRIGELAR', cnpj_remetente: '92660406006150', cliente_remetente: 'FRIGELAR COMERCIO E INDUSTRIA LT ..' },
  { curva_a: 'TEXTIL MN', cnpj_remetente: '97544848000202', cliente_remetente: 'MN ARMAZENS GERAIS LTDA ..' }
];

export const initialCidadesRotas: CidadeRota[] = [
  { cidade: 'VARGINHA', alias: 'VARGINHA-MG, VARGINHA MG, VAG, VGA', setor: 'ROTA 01', rota: 'ROTA 01', prazo_padrao: 1, prioridade_operacional: 'CRÍTICA', segunda: true, terca: true, quarta: true, quinta: true, sexta: true, cod: '1' },
  { cidade: 'ALFENAS', alias: 'ALFENA, ALFENAS-MG, ALFENAS MG', setor: 'ROTA 02', rota: 'ROTA 02', prazo_padrao: 2, prioridade_operacional: 'ALTA', segunda: true, terca: true, quarta: true, quinta: true, sexta: true, cod: '2' },
  { cidade: 'ELOI MENDES', alias: 'ELOI MENDES-MG, ELOI MENDES MG', setor: 'ROTA 02', rota: 'ROTA 02', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: true, quarta: true, quinta: true, sexta: true, cod: '2' },
  { cidade: 'MACHADO', alias: 'MACHADO-MG, MACHADO MG', setor: 'ROTA 02', rota: 'ROTA 02', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '2' },
  { cidade: 'PARAGUACU', alias: 'PARAGUACU-MG, PARAGUACU MG, PARAGUAÇU', setor: 'ROTA 02', rota: 'ROTA 02', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: true, quarta: true, quinta: true, sexta: true, cod: '2' },
  { cidade: 'BOA ESPERANCA', alias: 'BOA ESPERANCA-MG, BOA ESPERANÇA', setor: 'ROTA 03', rota: 'ROTA 03', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '3' },
  { cidade: 'CAMPO DO MEIO', alias: 'CAMPO DO MEIO-MG', setor: 'ROTA 03', rota: 'ROTA 03', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '3' },
  { cidade: 'CAMPOS GERAIS', alias: 'CAMPOS GERAIS-MG', setor: 'ROTA 03', rota: 'ROTA 03', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '3' },
  { cidade: 'COQUEIRAL', alias: 'COQUEIRAL-MG', setor: 'ROTA 03', rota: 'ROTA 03', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: true, quarta: true, quinta: true, sexta: true, cod: '3' },
  { cidade: 'NEPOMUCENO', alias: 'NEPOMUCENO-MG', setor: 'ROTA 03', rota: 'ROTA 03', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '3' },
  { cidade: 'SANTANA DA VARGEM', alias: 'SANTANA DA VARGEM-MG', setor: 'ROTA 03', rota: 'ROTA 03', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '3' },
  { cidade: 'TRES PONTAS', alias: 'TRES PONTAS-MG, TRÊS PONTAS', setor: 'ROTA 03', rota: 'ROTA 03', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '3' },
  { cidade: 'GUARANESIA', alias: 'GUARANESIA-MG, GUARANÉSIA', setor: 'ROTA 04', rota: 'ROTA 04', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '4' },
  { cidade: 'GUAXUPE', alias: 'GUAXUPE-MG, GUAXUPÉ', setor: 'ROTA 04', rota: 'ROTA 04', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '4' },
  { cidade: 'CAMPANHA', alias: 'CAMPANHA-MG', setor: 'ROTA 05', rota: 'ROTA 05', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '5' },
  { cidade: 'MONSENHOR PAULO', alias: 'MONSENHOR PAULO-MG', setor: 'ROTA 05', rota: 'ROTA 05', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '5' },
  { cidade: 'SAO GONCALO DO SAPUCAI', alias: 'SAO GONCALO DO SAPUCAI-MG, SÃO GONÇALO DO SAPUCAÍ', setor: 'ROTA 05', rota: 'ROTA 05', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '5' },
  { cidade: 'TRES CORACOES', alias: 'TRES CORACOES-MG, TRÊS CORAÇÕES', setor: 'ROTA 05', rota: 'ROTA 05', prazo_padrao: 1, prioridade_operacional: 'ALTA', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '5' },
  { cidade: 'CARMO DA CACHOEIRA', alias: 'CARMO DA CACHOEIRA-MG', setor: 'ROTA 06', rota: 'ROTA 06', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '6' },
  { cidade: 'IJACI', alias: 'IJACI-MG', setor: 'ROTA 06', rota: 'ROTA 06', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '6' },
  { cidade: 'LAVRAS', alias: 'LAVRAS-MG, LAVRAS MG', setor: 'ROTA 06', rota: 'ROTA 06', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: true, quarta: true, quinta: true, sexta: true, cod: '6' },
  { cidade: 'PERDOES', alias: 'PERDOES-MG, PERDÕES', setor: 'ROTA 06', rota: 'ROTA 06', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '6' },
  { cidade: 'CAMPO BELO', alias: 'CAMPO BELO-MG', setor: 'ROTA 06', rota: 'ROTA 06', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '6' },
  { cidade: 'CAMBUQUIRA', alias: 'CAMBUQUIRA-MG', setor: 'ROTA 07', rota: 'ROTA 07', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '7' },
  { cidade: 'CARMO DE MINAS', alias: 'CARMO DE MINAS-MG', setor: 'ROTA 07', rota: 'ROTA 07', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '7' },
  { cidade: 'CRISTINA', alias: 'CRISTINA-MG', setor: 'ROTA 07', rota: 'ROTA 07', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '7' },
  { cidade: 'SAO LOURENCO', alias: 'SAO LOURENCO-MG, SÃO LOURENÇO', setor: 'ROTA 07', rota: 'ROTA 07', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: true, quarta: true, quinta: true, sexta: true, cod: '7' },
  { cidade: 'BAEPENDI', alias: 'BAEPENDI-MG', setor: 'ROTA 08', rota: 'ROTA 08', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '8' },
  { cidade: 'CAXAMBU', alias: 'CAXAMBU-MG', setor: 'ROTA 08', rota: 'ROTA 08', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '8' },
  { cidade: 'CONCEICAO DO RIO VERDE', alias: 'CONCEICAO DO RIO VERDE-MG, CONCEIÇÃO DO RIO VERDE', setor: 'ROTA 08', rota: 'ROTA 08', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '8' },
  { cidade: 'JESUANIA', alias: 'JESUANIA-MG, JESUÂNIA', setor: 'ROTA 08', rota: 'ROTA 08', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '8' },
  { cidade: 'LAMBARI', alias: 'LAMBARI-MG', setor: 'ROTA 08', rota: 'ROTA 08', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '8' },
  { cidade: 'OLIMPIO NORONHA', alias: 'OLIMPIO NORONHA-MG, OLÍMPIO NORONHA', setor: 'ROTA 08', rota: 'ROTA 08', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '8' },
  { cidade: 'ITAMONTE', alias: 'ITAMONTE-MG', setor: 'ROTA 09', rota: 'ROTA 09', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '9' },
  { cidade: 'ITANHANDU', alias: 'ITANHANDU-MG', setor: 'ROTA 09', rota: 'ROTA 09', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '9' },
  { cidade: 'PASSA QUATRO', alias: 'PASSA QUATRO-MG', setor: 'ROTA 09', rota: 'ROTA 09', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '9' },
  { cidade: 'POUSO ALTO', alias: 'POUSO ALTO-MG', setor: 'ROTA 09', rota: 'ROTA 09', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: true, terca: false, quarta: true, quinta: false, sexta: true, cod: '9' },
  { cidade: 'PASSOS', alias: 'PASSOS-MG', setor: 'ROTA 10', rota: 'ROTA 10', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '10' },
  { cidade: 'SAO SEBASTIAO DO PARAISO', alias: 'SAO SEBASTIAO DO PARAISO-MG, SÃO SEBASTIÃO DO PARAÍSO', setor: 'ROTA 10', rota: 'ROTA 10', prazo_padrao: 2, prioridade_operacional: 'NORMAL', segunda: false, terca: true, quarta: false, quinta: true, sexta: false, cod: '10' }
];

